model_parameters:
  image_width: 160
  image_height: 64
  characters: "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 -'.,"
  blank_token: 63
  max_text_length: 10

dataset:
  train_data_path: "ocr_dataset/train"
  test_data_path: "ocr_dataset/test"

logging:
  log_dir: "ocr_logs"
  tensorboard_frequency: 1

training:
  batch_size: 32
  epochs: 100
  learning_rate: 0.0005
  patience: 5

fonts:
  default_font: "fonts/ARIAL.ttf"
  cursive_fonts:
    - "fonts/AlexBrush-Regular.ttf"
    - "fonts/DancingScript-Regular.ttf"
    - "fonts/GreatVibes-Regular.ttf"